### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by mb47** [mzytnicki/pansel#1]
Hi,

thanks for providing pansel -- it looks really useful.

I am hitting a compiler error when I run make:

```
/usr/bin/ld: cannot find /usr/lib64/libasan.so.5.0.0
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: pansel] Error 1
```

My compiler is g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22) on Rocky Linux 8.10. 

Do I need to install a different compiler, or is this just a case of this particular library missing?

thanks
Micha

**Comment by mzytnicki** [comment]
Thanks for the comment @mb47 
Would it be possible for you to edit the `Makefile`, and remove `-fsanitize=address` ?
This should solve the problem.  If you confirm, I will also remove (hide) it.
Thanks again!

**Comment by mb47** [comment]
Yes, that worked -- many thanks for the prompt reply! Problem solved.
