### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by mb47** [mzytnicki/pansel#2]
Hi,

I have done my first run of pansel and looking at the output, the number of colums there (n = 14) doesn't match the number of column headers described in README.md (n = 13).  Columns 5 and 6 in the output seem to contain similar, but slightly different numbers, so I assume it's one of these that hasn't been described - the rest of the column headers all seem to match the contents and make sense:

```
4       3       5000    -nan    1       1       4001    5000    28406   2       3       28424   4998    5000
5       5000    9949    0.334275        2       3       5001    6000    28424   4998    5000    28428   9949    9950
9       5003    10001   -nan    1       1       9001    10000   28426   5002    5003    28453   10001   10002
10      9999    14262   0.334271        2       3       10001   11000   28451   9998    9999    28455   14262   14263
14      10002   15007   -nan    1       1       14001   15000   28453   10001   10002   28491   15007   15007
15      14322   21078   -nan    1       1       15001   16000   28488   14320   14322   28511   21078   21084
21      15051   26091   -nan    1       1       21001   22000   28509   15043   15051   28523   26091   26093
26      21107   31075   -nan    1       1       26001   27000   28521   21107   21107   28536   31075   31076
31      26110   35718   -nan    1       1       31001   32000   28534   26109   26110   28557   35718   35720
35      31111   40678   -nan    1       1       35001   36000   28555   31111   31111   28595   40678   40678
```
Could you please check this and update the README accordingly?

many thanks
Micha

**Comment by mzytnicki** [comment]
Dear Micha,

Thanks for pointing this.  I updated the README accordingly, and I now mention that I move from a (proxy of) edit distance to a Jaccard index.

Does it fix the problem?

Yet, I am puzzled by your `-nan` it seems to me that something is wrong here.

**Comment by mb47** [comment]
Hi,

thanks, yes that helps!

Regarding the `-nan` issue: I have just finished the first pansel runs of whole chromosomes and roughly a third of the Jaccard index values are `-nan`. Is this because of division by zero? It would be great if you could look into this and provide a fix, if possible. 

I am attaching my little sample graph that I used for testing, so you can reproduce this (had to rename it to make the upload work, but it is GFA format really). 
Here is the command I used:

```
pansel \
-i $input \
-r "Hvulga_MorexV3#1#chr1H" \
> $output 2> pansel.log
```

This is data from barley and its wild relatives. Graph built with Progressive Cactus. The sample is a small regional subgraph from chromosome 1 that spans 100 kbp. 

thanks
Micha
[test.gfa.txt](https://github.com/user-attachments/files/17870748/test.gfa.txt)

**Comment by mzytnicki** [comment]
Oh, I see!
As far as I see, your genomes are very fragmented.  You can compute the number of scaffolds per chromosome with

    grep '^P' test.gfa.txt | cut -f 2 | cut -f -1 -d "[" | sort | uniq -c

For chr1, you have at least 10 scaffolds (except the reference).

Now, `pansel` follows these paths, splits them into bins of fixed size, and (somehow) computes a distance between each pair of paths (inside each bin).
If paths are broken, `pansel` just discard them.  For each bin, the number of paths is given in the 6th field of the output file.  A `1` just says that only the reference genome goes from one extremity of the bin to the other (and the others are split/broken).  A `nan` is thus somewhat logical here.

What do you think about it?

**Comment by mb47** [comment]
Yes, that makes complete sense -- if we don't have uninterrupted paths for at least two accessions within a block, computing any measure of diversity is impossible. So I guess for the purpose of plotting diversity it's a case of simply filtering out rows with `-nan.` 

Some more background to this: our full graph for the entire super-pangenome is far too big to do anything with -- 2.5 billion nodes. This is largely the result of millions of years of divergence between accessions, and the genomic repeat space, which is large (~80% of the genome) and extremely diverged. 

So we need to split the graph into chromosomes, which we did with ` vg chunk`. This is what seems to have introduced all the fragmented subrange paths -- in the full graph there don't seem to be any, only exactly one whole-chromosome path per accession.

This is perhaps out of scope for here, but would you happen to know what we can do about the fragmentation?

thanks
Micha

**Comment by mzytnicki** [comment]
Yup.  Are you using PGGB, MiniGraph, or MiniGraph-Cactus?

**Comment by mb47** [comment]
We used Progressive Cactus.

**Comment by mzytnicki** [comment]
My!  I did not expect this.  I never tried it, and cannot help here.  Why did not you choose MiniGraph-Cactus instead?  It does not work on your data?

**Comment by mb47** [comment]
I'd need to check with my colleague who built the graph. It may be to do with the resolution of the graph. 
Thanks for all your help anyway -- at least I can plot the Jaccard index as a trend along each chromosome, so that's helped me already!

**Comment by mzytnicki** [comment]
If you graph is complex, and you do not care too much with small variants (< 50bp), MiniGraph may be advised.

**Comment by mb47** [comment]
Yes, we did try minigraph, but there is a serious issue with underalignment of the highly diverged repeat regions. The resulting graph was mainly identical to the initial reference accession. My conclusion is that minigraph isn't great for a repeat-rich super-pangenome of diverged accessions. It worked great for the Hordeum vulgare pangenome we have just released.

**Comment by mzytnicki** [comment]
Thanks Micha for the information.  A super-pangenome still is challenging.
If `vg` does not work, `odgi` (such as `extract`) could perhaps help?
